// <auto-generated />
using System;
using HotelLux.Finance.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelLux.Finance.DataAccess.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260513140735_InitialFinanzas")]
    partial class InitialFinanzas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finanzas")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelLux.Finance.DataAccess.Entities.FacturaDetalleEntity", b =>
                {
                    b.Property<int>("IdFacturaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFacturaDetalle"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<string>("DescripcionItem")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion_item");

                    b.Property<decimal>("DescuentoLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_linea");

                    b.Property<Guid>("FacturaDetalleGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("factura_detalle_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<Guid?>("ReferenciaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_guid");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("referencia_tipo");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal_linea");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_item");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_linea");

                    b.Property<decimal>("ValorIvaLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_iva_linea");

                    b.HasKey("IdFacturaDetalle");

                    b.HasIndex("FacturaDetalleGuid")
                        .IsUnique();

                    b.HasIndex("IdFactura");

                    b.ToTable("factura_detalle", "finanzas");
                });

            modelBuilder.Entity("HotelLux.Finance.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<Guid>("ClienteGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_guid");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<decimal>("DescuentoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_total");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("EMI")
                        .HasColumnName("estado");

                    b.Property<Guid>("FacturaGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("factura_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("FechaEmision")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTimeOffset?>("FechaInhabilitacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_inhabilitacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD")
                        .HasColumnName("moneda");

                    b.Property<string>("MotivoInhabilitacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo_inhabilitacion");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("ObservacionesFactura")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observaciones_factura");

                    b.Property<string>("OrigenCanalFactura")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origen_canal_factura");

                    b.Property<Guid>("ReservaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_guid");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("saldo_pendiente");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("finance-service")
                        .HasColumnName("servicio_origen");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("SucursalGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_guid");

                    b.Property<string>("TipoFactura")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("RESERVA")
                        .HasColumnName("tipo_factura");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("ValorIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_iva");

                    b.HasKey("IdFactura");

                    b.HasIndex("ClienteGuid");

                    b.HasIndex("FacturaGuid")
                        .IsUnique();

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("SucursalGuid");

                    b.HasIndex("ReservaGuid", "Estado", "FechaEmision");

                    b.ToTable("factura", "finanzas");
                });

            modelBuilder.Entity("HotelLux.Finance.DataAccess.Entities.PagoEntity", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<string>("CodigoAutorizacion")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("codigo_autorizacion");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsPagoElectronico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_pago_electronico");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PEN")
                        .HasColumnName("estado_pago");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTimeOffset>("FechaPagoUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_pago_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdFactura")
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("USD")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("PagoGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pago_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ProveedorPasarela")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("proveedor_pasarela");

                    b.Property<string>("Referencia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("referencia");

                    b.Property<Guid>("ReservaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_guid");

                    b.Property<string>("RespuestaPasarela")
                        .HasColumnType("text")
                        .HasColumnName("respuesta_pasarela");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("finance-service")
                        .HasColumnName("servicio_origen");

                    b.Property<decimal>("TipoCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,4)")
                        .HasDefaultValue(1m)
                        .HasColumnName("tipo_cambio");

                    b.Property<string>("TransaccionExterna")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("transaccion_externa");

                    b.HasKey("IdPago");

                    b.HasIndex("PagoGuid")
                        .IsUnique();

                    b.HasIndex("ReservaGuid");

                    b.HasIndex("IdFactura", "EstadoPago", "FechaPagoUtc");

                    b.ToTable("pago", "finanzas");
                });

            modelBuilder.Entity("HotelLux.Finance.DataAccess.Entities.FacturaDetalleEntity", b =>
                {
                    b.HasOne("HotelLux.Finance.DataAccess.Entities.FacturaEntity", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("HotelLux.Finance.DataAccess.Entities.PagoEntity", b =>
                {
                    b.HasOne("HotelLux.Finance.DataAccess.Entities.FacturaEntity", "Factura")
                        .WithMany("Pagos")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("HotelLux.Finance.DataAccess.Entities.FacturaEntity", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
