// <auto-generated />
using System;
using HotelLux.Reservation.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelLux.Reservation.DataAccess.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    partial class ReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reservas")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelLux.Reservation.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("apellidos");

                    b.Property<Guid>("ClienteGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("direccion");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("ACT")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaInhabilitacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_inhabilitacion_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("MotivoInhabilitacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo_inhabilitacion");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("reservation-service")
                        .HasColumnName("servicio_origen");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_identificacion");

                    b.HasKey("IdCliente");

                    b.HasIndex("ClienteGuid")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("TipoIdentificacion", "NumeroIdentificacion", "Correo");

                    b.ToTable("cliente", "reservas");
                });

            modelBuilder.Entity("HotelLux.Reservation.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("CodigoReserva")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_reserva");

                    b.Property<string>("CreadoDesdeIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("creado_desde_ip");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<decimal>("DescuentoAplicado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_aplicado");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<bool>("EsWalkin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_walkin");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PEN")
                        .HasColumnName("estado_reserva");

                    b.Property<DateTimeOffset?>("FechaCancelacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_cancelacion_utc");

                    b.Property<DateTimeOffset?>("FechaConfirmacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_confirmacion_utc");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTimeOffset?>("FechaInhabilitacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_inhabilitacion_utc");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<DateTimeOffset>("FechaReservaUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_reserva_utc");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("MotivoInhabilitacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("motivo_inhabilitacion");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<string>("OrigenCanalReserva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origen_canal_reserva");

                    b.Property<Guid>("ReservaGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("SaldoPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo_pendiente");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("reservation-service")
                        .HasColumnName("servicio_origen");

                    b.Property<decimal>("SubtotalReserva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal_reserva");

                    b.Property<Guid>("SucursalGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_guid");

                    b.Property<decimal>("TotalReserva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_reserva");

                    b.Property<decimal>("ValorIva")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_iva");

                    b.HasKey("IdReserva");

                    b.HasIndex("CodigoReserva")
                        .IsUnique();

                    b.HasIndex("ReservaGuid")
                        .IsUnique();

                    b.HasIndex("IdCliente", "EstadoReserva");

                    b.HasIndex("SucursalGuid", "FechaInicio", "FechaFin");

                    b.ToTable("reserva", "reservas");
                });

            modelBuilder.Entity("HotelLux.Reservation.DataAccess.Entities.ReservaHabitacionEntity", b =>
                {
                    b.Property<int>("IdReservaHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva_habitacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReservaHabitacion"));

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<decimal>("DescuentoLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento_linea");

                    b.Property<string>("EstadoDetalle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PEN")
                        .HasColumnName("estado_detalle");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<Guid>("HabitacionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("habitacion_guid");

                    b.Property<int>("IdReserva")
                        .HasColumnType("integer")
                        .HasColumnName("id_reserva");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<int>("NumAdultos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("num_adultos");

                    b.Property<int>("NumNinos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("num_ninos");

                    b.Property<decimal>("PrecioNocheAplicado")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_noche_aplicado");

                    b.Property<Guid>("ReservaHabitacionGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_habitacion_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("reservation-service")
                        .HasColumnName("servicio_origen");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal_linea");

                    b.Property<Guid?>("TarifaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("tarifa_guid");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_linea");

                    b.Property<decimal>("ValorIvaLinea")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_iva_linea");

                    b.HasKey("IdReservaHabitacion");

                    b.HasIndex("ReservaHabitacionGuid")
                        .IsUnique();

                    b.HasIndex("IdReserva", "HabitacionGuid", "FechaInicio")
                        .IsUnique();

                    b.ToTable("reserva_habitacion", "reservas");
                });

            modelBuilder.Entity("HotelLux.Reservation.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.HasOne("HotelLux.Reservation.DataAccess.Entities.ClienteEntity", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("HotelLux.Reservation.DataAccess.Entities.ReservaHabitacionEntity", b =>
                {
                    b.HasOne("HotelLux.Reservation.DataAccess.Entities.ReservaEntity", "Reserva")
                        .WithMany("ReservasHabitaciones")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("HotelLux.Reservation.DataAccess.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelLux.Reservation.DataAccess.Entities.ReservaEntity", b =>
                {
                    b.Navigation("ReservasHabitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
