// <auto-generated />
using System;
using HotelLux.Stay.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelLux.Stay.DataAccess.Migrations
{
    [DbContext(typeof(StayDbContext))]
    [Migration("20260514034919_AddNombreVisibleClienteToValoracion")]
    partial class AddNombreVisibleClienteToValoracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hospedaje")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelLux.Stay.DataAccess.Entities.CargoEstadiaEntity", b =>
                {
                    b.Property<int>("IdCargoEstadia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cargo_estadia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCargoEstadia"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<Guid>("CargoGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CatalogoGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogo_guid");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<string>("DescripcionCargo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("descripcion_cargo");

                    b.Property<string>("EstadoCargo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("PEN")
                        .HasColumnName("estado_cargo");

                    b.Property<DateTimeOffset>("FechaConsumoUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_consumo_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<int>("IdEstadia")
                        .HasColumnType("integer")
                        .HasColumnName("id_estadia");

                    b.Property<string>("ModificacionIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("modificacion_ip");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("stay-service")
                        .HasColumnName("servicio_origen");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalCargo")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_cargo");

                    b.Property<decimal>("ValorIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_iva");

                    b.HasKey("IdCargoEstadia");

                    b.HasIndex("CargoGuid")
                        .IsUnique();

                    b.HasIndex("IdEstadia", "EstadoCargo", "FechaConsumoUtc");

                    b.ToTable("cargo_estadia", "hospedaje");
                });

            modelBuilder.Entity("HotelLux.Stay.DataAccess.Entities.EstadiaEntity", b =>
                {
                    b.Property<int>("IdEstadia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_estadia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadia"));

                    b.Property<Guid>("ClienteGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_guid");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<Guid>("EstadiaGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("estadia_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("estado_estadia");

                    b.Property<DateTimeOffset?>("FechaCheckinUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("checkin_utc");

                    b.Property<DateTimeOffset?>("FechaCheckoutUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("checkout_utc");

                    b.Property<DateTimeOffset?>("FechaModificacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_modificacion_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<Guid>("HabitacionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("habitacion_guid");

                    b.Property<string>("ModificadoPorUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modificado_por_usuario");

                    b.Property<string>("ObservacionesCheckin")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones_checkin");

                    b.Property<string>("ObservacionesCheckout")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones_checkout");

                    b.Property<bool>("RequiereMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_mantenimiento");

                    b.Property<Guid>("ReservaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_guid");

                    b.Property<Guid>("ReservaHabitacionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_habitacion_guid");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("stay-service")
                        .HasColumnName("servicio_origen");

                    b.Property<Guid>("SucursalGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_guid");

                    b.HasKey("IdEstadia");

                    b.HasIndex("EstadiaGuid")
                        .IsUnique();

                    b.HasIndex("ReservaGuid", "Estado");

                    b.ToTable("estadia", "hospedaje");
                });

            modelBuilder.Entity("HotelLux.Stay.DataAccess.Entities.ValoracionEntity", b =>
                {
                    b.Property<int>("IdValoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_valoracion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdValoracion"));

                    b.Property<Guid>("ClienteGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_guid");

                    b.Property<string>("ComentarioNegativo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario_negativo");

                    b.Property<string>("ComentarioPositivo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario_positivo");

                    b.Property<string>("CreadoPorUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("creado_por_usuario");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_eliminado");

                    b.Property<Guid>("EstadiaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("estadia_guid");

                    b.Property<DateTimeOffset>("FechaPublicacionUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_publicacion_utc");

                    b.Property<DateTimeOffset>("FechaRegistroUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_registro_utc");

                    b.Property<string>("NombreVisibleCliente")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_visible_cliente");

                    b.Property<decimal>("PuntuacionCalidadPrecio")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("puntuacion_calidad_precio");

                    b.Property<decimal>("PuntuacionConfort")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("puntuacion_confort");

                    b.Property<decimal>("PuntuacionGeneral")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("puntuacion_general");

                    b.Property<decimal>("PuntuacionInstalaciones")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("puntuacion_instalaciones");

                    b.Property<decimal>("PuntuacionLimpieza")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("puntuacion_limpieza");

                    b.Property<decimal>("PuntuacionPersonal")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("puntuacion_personal");

                    b.Property<decimal>("PuntuacionUbicacion")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("puntuacion_ubicacion");

                    b.Property<string>("RespuestaHotel")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("respuesta_hotel");

                    b.Property<Guid>("SucursalGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("sucursal_guid");

                    b.Property<string>("TipoViaje")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_viaje");

                    b.Property<Guid>("ValoracionGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("valoracion_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.HasKey("IdValoracion");

                    b.HasIndex("ClienteGuid");

                    b.HasIndex("EstadiaGuid");

                    b.HasIndex("SucursalGuid");

                    b.HasIndex("ValoracionGuid")
                        .IsUnique();

                    b.ToTable("valoracion", "hospedaje");
                });

            modelBuilder.Entity("HotelLux.Stay.DataAccess.Entities.CargoEstadiaEntity", b =>
                {
                    b.HasOne("HotelLux.Stay.DataAccess.Entities.EstadiaEntity", "Estadia")
                        .WithMany("Cargos")
                        .HasForeignKey("IdEstadia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estadia");
                });

            modelBuilder.Entity("HotelLux.Stay.DataAccess.Entities.EstadiaEntity", b =>
                {
                    b.Navigation("Cargos");
                });
#pragma warning restore 612, 618
        }
    }
}
