// <auto-generated />
using System;
using HotelLux.Audit.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelLux.Audit.DataAccess.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auditoria")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelLux.Audit.DataAccess.Entities.EventoAuditoriaEntity", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAuditoria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<Guid>("AuditoriaGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("auditoria_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_anteriores");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_nuevos");

                    b.Property<Guid?>("EntidadGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_guid");

                    b.Property<DateTimeOffset>("FechaEventoUtc")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnName("fecha_evento_utc");

                    b.Property<string>("IdRegistroAfectado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_registro_afectado");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("operacion");

                    b.Property<string>("ServicioOrigen")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("servicio_origen");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabla_afectada");

                    b.Property<string>("UsuarioEjecutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuario_ejecutor");

                    b.Property<Guid?>("UsuarioGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_guid");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("EntidadGuid");

                    b.HasIndex("FechaEventoUtc");

                    b.HasIndex("ServicioOrigen", "FechaEventoUtc");

                    b.HasIndex("TablaAfectada", "FechaEventoUtc");

                    b.HasIndex("UsuarioEjecutor", "FechaEventoUtc");

                    b.ToTable("evento_auditoria", "auditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
